
#include <stdio.h>
#include <stdlib.h>
#include "naloga2.h"

char* NIZI[] = {
    "xI7pEdBHH",
    "zLS5",
    "EgzbWx4G",
    "q",
    "SkW1ELFBff",
    "f",
    "Nn",
    "cd75NBHJ",
    "9TH",
    "gm8TCrr",
    "7b7HU4S",
    "CFt8A",
    "XC",
    "_J",
    "Kwp",
    "uPom4WCNxp",
    "eQvbny",
    "wr",
    "iSaROxQyb",
    "UCya58JiXU",
    "vW5w8kL3",
    "Oev0a",
    "MGw",
    "aD",
    "Il",
    "fOMMeNn6mP",
    "riX",
    "uvgsAP4Hkz",
    "SzUWlsvZiR",
    "x3Jl6B",
    "WBoi",
    "c_4wQvnIul",
    "Z_Hxz5GH3",
    "By8VoqNsUx",
    "q",
    "d1",
    "xl",
    "kDE7",
    "H",
    "W",
    "I5u0cflrdj",
    "erprCMP",
    "11l1y_",
    "nTnIBj",
    "xgZK3U",
    "0ArxyaA9J",
    "L2T2cJ",
    "OlVUUXtWz",
    "KbjYwC3P",
    "7wNq_QRs",
    "evUNb",
    "P3qy7_VL",
    "hG4wQcG",
    "xoWED6eoog",
    "jbd",
    "LwG8NKe",
    "6a53Cq",
    "icS_ugl",
    "qc",
    "XcMmyH_M05",
    "IsfaLz",
    "y",
    "1HIN2uO",
    "ovYzvA88",
    "YgU",
    "YvhD",
    "BAoqzmF",
    "k",
    "eRfJT6Q1I",
    "VUMuRY",
    "ZBePf3Wu",
    "PvQ4P7EE9R",
    "SYZUIg1t",
    "DJf12o5Zp",
    "bC3I6k7Zl",
    "Zk",
    "ct24TFOE",
    "NyH",
    "E",
    "A",
    "Qd3SX",
    "Kz",
    "9csBVKX",
    "A1dS5VR",
    "tD3vpPSdM3",
    "5vY",
    "yLjGvOcdYH",
    "sLM0iqUviR",
    "kDgEHmg5_",
    "7XIW",
    "MDFqsjYqf",
    "kVIO52HW",
    "5YT",
    "Rf_WYpnq",
    "u",
    "r96QEUVwX",
    "WgmXk",
    "tzJnhRK",
    "Ab77",
};

int main() {
    int stIzhodnih = 0;
    char** izhodni = poStolpcih(NIZI, sizeof(NIZI) / sizeof(NIZI[0]), &stIzhodnih);
    printf("%d\n", stIzhodnih);

    for (int i = 0; i < stIzhodnih; i++) {
        printf("%d: \"%s\"\n", i, izhodni[i]);
        free(izhodni[i]);
    }
    free(izhodni);
    return 0;
}
